import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import Footer from '../components/Footer.js';
import NavArea from '../components/NavArea';
import HomeCard from '../components/HomeCard';
import { URL_PREFIX } from '../zothers/GlobalVar';

class Home extends React.Component {
  constructor(props) {
    super(props);

    this.page = 1;
    this.tryToLoadMore = this.tryToLoadMore.bind(this);
    this.loadArticlesFromServer = this.loadArticlesFromServer.bind(this);
    this.state = { itemList: props.initialArticleList }
  }

  componentDidMount() {
    this.loadArticlesFromServer();
  }

  tryToLoadMore() {
    console.log("tryToLoadMore");

    this.page++;
    this.loadArticlesFromServer();
  }

  async loadArticlesFromServer() {
    // const theUrl = "https://codernong.com:9002/articles?page=" + this.page;
    const theUrl = URL_PREFIX + "articles?page=" + this.page;
    const articlesData = await fetch(theUrl);
    const articlesJson = await articlesData.json();
    const articleList = articlesJson["data"];

    var newestArticles = this.state.itemList;

    Array.prototype.push.apply(newestArticles, articleList);

    this.setState({ itemList: newestArticles });
  }

  render() {
    return (
      <div className="container mx-auto">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        </Head>

        <NavArea />

        <div className='px-2 py-2 columns-2xs ' id='groundarea'>
          {this.state.itemList.map((item, idx) => {
            return <HomeCard key={idx} index={idx} itemData={item} />
          })}
        </div>

        <div className='px-4' id="buttonLoadMore">
          <button className="w-full h-10 mt-3 py-2 px-4 bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75" onClick={this.tryToLoadMore}>
            加载更多
          </button>
        </div>

        <Footer />
      </div>
    )
  }
}

export default Home;

export async function getStaticProps(context) {
  // const theUrl = "http://127.0.0.1:9002/articles?page=0";
  console.log("URL_PREFIX:", URL_PREFIX);
  const theUrl = URL_PREFIX + "articles?page=0";
  const articlesData = await fetch(theUrl);
  const articlesJson = await articlesData.json();
  const initialArticleList = articlesJson["data"];

  return {
      props: {
        initialArticleList
      }
  }
}



/*
瀑布流布局：
https://juejin.cn/post/6844904051310592014
*/