import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import Footer from '../components/Footer.js';
import NavArea from '../components/NavArea';
import HomeCard from '../components/HomeCard';

class Home extends React.Component {
  constructor(props) {
    super(props);

    this.page = 0;
    this.tryToLoadMore = this.tryToLoadMore.bind(this);
    this.loadArticlesFromServer = this.loadArticlesFromServer.bind(this);
    this.state = { itemList: [] }
  }

  componentDidMount() {
    this.loadArticlesFromServer();
  }

  tryToLoadMore() {
    console.log("tryToLoadMore");

    this.page++;
    this.loadArticlesFromServer();
  }

  async loadArticlesFromServer() {
    const theUrl = "http://127.0.0.1:9002/articles?page=" + this.page;
    const articlesData = await fetch(theUrl);
    const articlesJson = await articlesData.json();
    const articleList = articlesJson["data"];
    console.log("articleList:", articleList);    

    this.state.itemList.push(articleList[this.page]);

    console.log("itemListitemList:", this.state.itemList);
    var newestArticles = this.state.itemList;
    // var newestArticles = [...this.state.itemList, ...articleList];
    // this.state.itemList.forEach(e => {
    //   newestArticles.push(e);
    // });
    // newestArticles = newestArticles.concat(this.state.itemList);
    // console.log("newestArticles1111:", newestArticles);
    // for (let e in this.state.itemList) {
    //   newestArticles.push(e);
    // }
    // articleList.forEach(e => {
    //   newestArticles.push(e);
    // });
    // newestArticles = newestArticles.concat(articleList);
    // console.log("newestArticles2222:", newestArticles);    
    // if (this.page > 0) {
    //   Array.prototype.push.apply(newestArticles, this.state.itemList);
    // }

    Array.prototype.push.apply(newestArticles, articleList);
    
    this.setState({ itemList: newestArticles });
    console.log("newestArticles: ", articleList.length);
  }

  render() {
    return (
      <div className="container mx-auto">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavArea />

        <div className='px-2 py-2 columns-2xs ' id='groundarea'>
          {this.state.itemList.map((item, idx) => {
            return <HomeCard key={idx} index={idx} itemData={item} />
          })}
        </div>

        <button className="w-full mt-3 py-2 px-4 bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75" onClick={this.tryToLoadMore}>
          加载更多
        </button>

        <Footer />
      </div>
    )
  }
}

export default Home;
